### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by JustAnotherVar** [Huzuni/Huzuni-1.11#15]
This mod conflicts with minimap mod such as [Xaero's Minimap](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2379024-xaeros-minimap-forge-1-11-2-1-11-1-10-2-1-10-1-9-4) and [Mapwriter](https://mods.curse.com/mc-mods/Minecraft/231387-mapwriter-2).  

Xaero's Minimap:  
Does not display the map at all, seems it have been overridden
Mapwriter:
The world map is reporting incorrect coordinates https://i.imgur.com/sMOAt9r.png  

The chat output to latest.log is inconsistent  
In game https://i.imgur.com/qEhioVy.png  
latest.log http://pastebin.com/ZSmNPngu  

unrelated [pic](https://i.imgur.com/tjzFZ8Z.png) and [crash log](http://pastebin.com/NEjiEV4u)
Is there any way to prevent the override of the "vanilla" main menu?

**Comment by brudin** [comment]
Chat log is fixed for the next release, I think I know what's causing the minimap bugs, it's our class overrides, which is also being fixed. Thanks!

**Comment by imaBASKET** [comment]
Can we expect a release sometime soon? I attempted building it myself however none of the three jars it produced did anything.
