### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by NilssMiner99** [Huzuni/Huzuni-1.11#20]
When you activate Projectiles then the screen is grey and the game crash

**Comment by brudin** [comment]
This is fixed for the next release

**Comment by NilssMiner99** [comment]
and by other module is it too

**Comment by NilssMiner99** [comment]
imput string error "1.2"

**Comment by NilssMiner99** [comment]
try
{
}
 catch(Exeption ex)
{
}


??? xD

**Comment by NilssMiner99** [comment]
it is when you change a number value
