### ISSUE TITLE
kill-aura issues

### ISSUE THREAD

**Issue by heyitslxxd** [Huzuni/Huzuni-1.11#22]
when i try to modify speed, the game crash.

**Comment by brudin** [comment]
This is fixed for the next release

**Comment by heyitslxxd** [comment]
thanks <3
and u can add a hide Huzuni option ?

**Comment by heyitslxxd** [comment]
p.s:
fix for 1.8 too (the kill-aura issue)

**Comment by brudin** [comment]
Yeah, if the disable Huzuni option doesn't make it to the next update, it'll definitely be added shortly after.
This bug will also be fixed for 1.8 since we're going to be able to update all versions at once, fun!

**Comment by heyitslxxd** [comment]
ok thanks for replying! <3 love u so much!

**Comment by heyitslxxd** [comment]
it will take a long time to launch this update?

**Comment by heyitslxxd** [comment]
Sorry for asking too much!

**Comment by brudin** [comment]
No worries! I'm not too sure. It's going to be a week or two, buy after it's out we will be update the client much more often.

**Comment by heyitslxxd** [comment]
Any update? I've been waiting for 3 months. :/ :(
