### ISSUE TITLE
release

### ISSUE THREAD

**Issue by imaBASKET** [Huzuni/Huzuni-1.11#34]
Any chance we can get a release soon?

I'm hoping to use the version which has mapwriter fixed however I've tried building from several commits since then and the resulting jars created crash the game.

thanks.

**Comment by brudin** [comment]
Trust me, I definitely want this out ASAP!

Thankfully, there's only a few things left to do, which is finish porting the render methods away from Minecraft, and fixing some bugs with our PlaceTask so mods like Replica/AutoHarvest will work again.

Out of curiosity, what were the crashes you were getting with your attempts to build the jars?

**Comment by imaBASKET** [comment]
I built several versions

Here are the crash logs:
https://pastebin.com/1gsnVAqr
https://pastebin.com/ddcRDvD7
https://pastebin.com/HSS2FFj7

What's interesting though is that I built based off the commit of the last release and it worked fine, however something between now and then has made it not work.

**Comment by imaBASKET** [comment]
This is for sure the crash error for 5.0.3-full
https://pastebin.com/UQAfNJET

**Comment by imaBASKET** [comment]
Interesting, I narrowed down the issue to script manager then using the current source removed all traces of it. It seems to work fine, however the main menu seems to be a bit strange and of course script manager no longer works.

http://i.imgur.com/7nRPo8I.png

**Comment by brudin** [comment]
Hahaha yeah, menu edits are gonna look pretty weird for some mods.  Beautiful. :,)

I'll take a look at our script manager, thanks!

**Comment by imaBASKET** [comment]
One of the latest commits seems to have fixed the script manager.
