### ISSUE TITLE
ESP box color

### ISSUE THREAD

**Issue by imaBASKET** [Huzuni/Huzuni-1.11#38]
I've tried changing the code to no avail on the color of the ESP boxes. Currently they are a dark grey and not very easy to see. Would be nice if they were made a more noticeable color or give an option to change it similarly to how you can change the gui color.

**Comment by brudin** [comment]
The ESP color shouldn't be grey, they should be red/green depending on specific circumstances.  Could you share your specs?  Might be an issue with your GPU and OpenGL

**Comment by imaBASKET** [comment]
Specs:
http://i.imgur.com/AZz7b9w.png

Picture of what it looks like:
http://i.imgur.com/AZz7b9w.png

**Comment by brudin** [comment]
You posted the same picture twice, lol

**Comment by imaBASKET** [comment]
shit your right

heres what it looks like:
http://i.imgur.com/rVqbhPl.png

**Comment by brudin** [comment]
Thanks!
I'm not able to replicate this issue on my end - is this happening on the other ESP modes too?

**Comment by imaBASKET** [comment]
Yes it happens on every mode.

**Comment by brudin** [comment]
Yeah, that is strange.

The Box mode uses different coloring methods than the tracers do, but the other ESP modes use the same coloring methods.

Your graphics card drivers are all up to date too, right?

**Comment by imaBASKET** [comment]
Yes

**Comment by Hexeption** [comment]
Looks like a GL issue, what other mods are enabled ?

**Comment by imaBASKET** [comment]
Mod list:
http://i.imgur.com/gRUX22q.png

**Comment by imaBASKET** [comment]
Narrowed the issue down to a world edit mod which displays your selection

Interestingly it was the forge version of the mod, but the liteloader version does not have this problem.

Thanks.

**Comment by brudin** [comment]
Thanks, saved me a bit of time trying to figure out what would be causing it haha
