### ISSUE TITLE
NoHurtCam

### ISSUE THREAD

**Issue by imaBASKET** [Huzuni/Huzuni-1.11#39]
Would be nice to have the option to disable the damage animation

Like so:
https://www.youtube.com/watch?v=MZsOmpBrFcY

**Comment by imaBASKET** [comment]
I've looked into this and it seems to be just as simple as disabling hurtCameraEffect in EntityRenderer.java, however while I have it working in a standalone modified vanilla jar, I'm unsure of how you would add it to something like this, a forge mod.

**Comment by brudin** [comment]
Its entirely possible, I'll look into adding this.
