### ISSUE TITLE
Settings Don't Save

### ISSUE THREAD

**Issue by lindinoPT** [Huzuni/Huzuni-1.11#40]
Launching Minecraft with Huzuni installed properly (huzuni folder containing the .jar in /versions) all the hacks work, customizing Huzuni works completely too, adding waypoints works - everything. However when I close Minecraft, everything I've set previously, like the menu colours / waypoints, are ALL GONE. I have to re-set everything and this is very tedious and annoying. I don't know what's causing the issue whatsoever. :)

**Comment by brudin** [comment]
This version of the client (forge version) has this fixed. :)

**Comment by lindinoPT** [comment]
Wait so, I'm installing everything right? I just have the wrong version? Could you send me a link to the most recent version of Huzuni, I thought I had it.. :/

**Comment by brudin** [comment]
http://halalaboos.net/

(For now) the client requires Forge to be installed, then you just drag it into the mods folder in your .minecraft.

The next update will no longer require Forge, just gotta fix some bugs so that people can use it with/without Forge if they want to

**Comment by lindinoPT** [comment]
Yeah, this worked! Thank you very much! :) I didn't know that wizardhax was claiming to be the owner, they should at least link it to halalaboos.net...

**Comment by brudin** [comment]
Yeah, they're being really difficult about this.
