### ISSUE TITLE
.command escape

### ISSUE THREAD

**Issue by addles** [Huzuni/Huzuni-1.11#41]
Can you add a way to escape the .commands in the chat? so we can type with a dot at the beginning of our chat msg.

Thanks

**Comment by brudin** [comment]
For now you can do '.say .help', though I'd love to have something like '~.help' like we had on the earlier versions.

**Comment by lindinoPT** [comment]
Yeah, I agree with this. It should be custom binded to something, or even add a console because if someone gets you to type .help or .<anything> then you easily get caught out because it won't appear in chat.

**Comment by brudin** [comment]
I have added a '~.message' thing to the client, which will just strip the '~' character in the beginning and send the message (so ~.foo becomes .foo).

If this isn't really what you were requesting, feel free to re-open the issue!
