### ISSUE TITLE
Huzuni Cape (1.8)

### ISSUE THREAD

**Issue by ArticMelon** [Huzuni/Huzuni-1.11#46]
I purchased a huzuni cape for me & my friend (ArticMelon & superbaba2) & now it has disappeared. (I posted it on 1.11 because I couldn't figure out how to post on 1.8) Please restore the cape, as I paid collectively $10 for them. Thank you! :)

**Comment by ili-codes** [comment]
AFAIK Huzuni doesn't sell capes. You probably downloaded the fake Huzuni, which is **not** the original version.

**Comment by ArticMelon** [comment]
@ili-codes Well, it wasn't just the cape. Back then I bought the VIP & the cape was an added bonus. It was a dark gray outline, a cyan lowercase h in the middle surrounded by light gray.

**Comment by brudin** [comment]
@ili-codes We had donations a few years back, that's probably what they're referring to

On the topic of capes - we definitely want to come up with a way of thanking those who donated years back, but right now there is some behind-the-scenes stuff regarding capes that's getting in the way.  

Hopefully this can be resolved soon!

**Comment by ArticMelon** [comment]
@brudin Once you implement them back, will it be over all huzuni platforms or only the new versions?

**Comment by brudin** [comment]
The upcoming update allows us to update the client for multiple versions with ease, so you'll see them in all versions. :+1:

**Comment by ArticMelon** [comment]
@Bryson Sweet, thanks for letting me know! :)
