### ISSUE TITLE
"Fire Blocker"

### ISSUE THREAD

**Issue by ConsoleHack000** [Huzuni/Huzuni-1.11#51]
So guys came here with a quick idea: A client side hack which basically removes that annoying fire overlay thingy that comes when your player is on fire. Its really annoying and blocks half of your screen. I think replacing it with text or a small icon somewhere on the screen is a good idea so the player can still know they're on fire but it doesn't annoy them as much. Thanks in advance :D

**Comment by brudin** [comment]
This is included in the 'No effect' mod that will be in the next update. 

The status text thing is a good idea though, we could probably add that as a widget or something!

**Comment by ConsoleHack000** [comment]
Cool! Waiting for the next update! 
Thank god I found the real huzuni website/devs, I was going to use the ones from wizardhax which yeaa... are bad......
