### ISSUE TITLE
I can't change theme !!!!

### ISSUE THREAD

**Issue by MiChU2137** [Huzuni/Huzuni-1.11#6]
#I can't change theme !!!! Help pls !!!!!!!!!!!!!!!!

**Comment by brudin** [comment]
The click GUI only has the Basic theme in this version.  We're currently redoing the GUI and will add more themes once that's done.

The ingame HUD is still themeable though, look at the **Widgets** tab in the GUI for configuration options, you can also drag the elements around!

I'm going to keep this issue open just in case anyone else has a similar report.
