### ISSUE TITLE
I accidentally deleted the HackGUI bind for rshift, how do I fix it?

### ISSUE THREAD

**Issue by Confused66** [Huzuni/Huzuni-1.11#70]
I accidentally deleted the HackGUI bind for rshift, how do I fix it or what button opens it now?

EDIT : Fixed just delete every trace of huzuni you have for that certain type of minecraft like 1.8 1.9 etc, then redownload it.

**Comment by TheForgottenKing** [comment]
.bind Hackgui <letter>

**Comment by Confused66** [comment]
It says hackgui and click gui aren't mods, how do do the Huzuni config thing?
