### ISSUE TITLE
Crash When startup

### ISSUE THREAD

**Issue by ABCLost** [Huzuni/Huzuni-1.11#8]
Followed the isntallation guide but im getting a crash all the time.
Huzuni Version: 1.8.8 / Forge same version.
Log: 

[Log.zip](https://github.com/Huzuni/Huzuni-1.11/files/785519/Log.zip)

**Comment by brudin** [comment]
Are you sure this is the entire log? This doesn't have the actual crash log itself, just the Forge 'fake crash' thing it does when setting up the game.

**Comment by ABCLost** [comment]
Fake so i just have to let it load even it says Not Reacting? Bescause without the mod it loads but with the mod it crashed,

**Comment by ABCLost** [comment]
It was the full log,

**Comment by ABCLost** [comment]
![crash](https://cloud.githubusercontent.com/assets/20955834/23105639/946b313a-f6e2-11e6-8a49-e6fd1d45af0b.png)

**Comment by brudin** [comment]
Can you go to `.minecraft\crash-reports` and send me the most recent crash log?

**Comment by ABCLost** [comment]
Im using the newest launcher might bescause of that? would like the old launcher back,
I just tried by using the WURST Client ( just a version ) looking if that would crash but that crashed also,
Also reinstalled java,
[Latest.zip](https://github.com/Huzuni/Huzuni-1.11/files/786127/Latest.zip)

**Comment by ABCLost** [comment]
Maybe the Launcher_log can help you?

**Comment by brudin** [comment]
Is there a crash-reports folder in your .minecraft folder?

**Comment by ABCLost** [comment]
No. second i will send picture of the entire .minecraft
![minecraft](https://cloud.githubusercontent.com/assets/20955834/23105934/bb915970-f6e6-11e6-8c24-e6ccbd6be82a.png)

**Comment by ABCLost** [comment]
[Launcher_log.zip](https://github.com/Huzuni/Huzuni-1.11/files/786144/Launcher_log.zip)
This is the Launcher_log

**Comment by brudin** [comment]
Alright, if there's a fml-client-latest log file in the logs file, that should have the full crash report

**Comment by ABCLost** [comment]
Doesnt have one

**Comment by ABCLost** [comment]
maybe i need an older java version?

**Comment by brudin** [comment]
Nah, Java 8 is the correct version.  If it's happening with other clients too I recommend you just use the older launcher for now. 

https://minecraft.net/en-us/download/alternative

**Comment by brudin** [comment]
Can you post a picture of what the logs folder looks like?

**Comment by ABCLost** [comment]
![log](https://cloud.githubusercontent.com/assets/20955834/23106041/0ca59d98-f6e8-11e6-8910-0cc8196a4e3c.png)

**Comment by ABCLost** [comment]
The old launcher gives me an other freaking error but just by loading the game not by using forge or anything else 
![log](https://cloud.githubusercontent.com/assets/20955834/23106099/ad5337c8-f6e8-11e6-87c3-8412e9f60545.png)

**Comment by brudin** [comment]
http://nvidia.custhelp.com/app/answers/detail/a_id/4378/?utm_content=buffer0ece9&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer

Are you using an NVIDIA card?

**Comment by ABCLost** [comment]
Yes im.

**Comment by brudin** [comment]
Update the driver, there was a crash issue with one of the recent updates

**Comment by ABCLost** [comment]
Thanks alot, hope this works now my Nvidia Geforce Experience application didnot tell me there is an update.

**Comment by ABCLost** [comment]
It worked just one question, anyway i can change keybindings of some of the features of the hack? like Sneak etc,

**Comment by brudin** [comment]
Yep!

Press right shift to open the settings GUI, then click the arrow to open the mod settings, then click the settings button and then click the Keybind button to change the key: http://i.imgur.com/p2lmVZM.png

This will be a bit more clear once the new GUI is done
