### ISSUE TITLE
Huzuni crash when i change options ( killaura reach or speed)

### ISSUE THREAD

**Issue by Czekoladowy** [Huzuni/Huzuni-1.11#9]

**Comment by brudin** [comment]
Can you post the crash log?

**Comment by Czekoladowy** [comment]
![przechwytywanie](https://cloud.githubusercontent.com/assets/26094744/23459615/7649024e-fe81-11e6-8e25-a7101fd92e11.PNG)

**Comment by brudin** [comment]
Oooh, I think I know what's causing this.
This is when you change the values in the GUI, right? Not the config file?
The main issue is it should be formatting the values like "9.4" but instead is doing "9,4"

**Comment by Czekoladowy** [comment]
Yes i change in the GUI how can i repeir this?

**Comment by brudin** [comment]
This will be fixed in the next release, thanks!
